- name: "Create keycloak container"
  local_action:
    module: community.general.terraform
    project_path: "../terraform/"
    state: present
    variables:
      pm_api_url: "{{ pm.api_url }}"
      pm_user: "{{ pm.user }}"
      pm_password: "{{ pm.password }}"
      sshkey: "{{ sshkey }}"