- name: "Create Linux containers services"
  local_action:
    module: community.general.terraform
    project_path: "../terraform/"
    state: present
    variables:
      #PROXMOX
      pm_api_url: "{{ pm.api_url }}"
      pm_user: "{{ pm.user }}"
      pm_password: "{{ pm.password }}"
      #MISCELLANEOUS
      sshkey: "{{ sshkey }}"
      nodes: "{{ nodes }}"
      #SERVICES
      
      