- name: "Create keycloak container"
  local_action:
    module: community.general.terraform
    project_path: "../terraform/"
    state: present
    variables:
      pm_password: "{{ pm.password }}"
      sshkey: "{{ sshkey }}"


