
#PROXMOX VARIABLES
pm:
  api_url: "https://192.168.20.53:8006/api2/json"
  user: "root@pam"
  password: "P@ssw0rd"

#MISCELLANEOUS
sshkey : "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCcPfgyf9Q+yhR2hATV/RA2ukL6WbfV8ys/Lij8BLCL+HfaosjbI5NVLHaqoiDL9P4Am5pnlyj5s0GfsaX/OeHQwe6YhC1bkgpJSEI+gRdoGtzK3YlPBIV+QvK5fQRLCu4ADz6VxcpAIC/PxBa4mkaj5M/uO6veicXgyXJVewo+XR6Z1QXAdR12agt44GENcUVC+/RGShhAkJ6YBylZ34tk0ZtKmFMslxMB6+xF8J+t+vKr7yrg8Vha/J0gR/Feu4qDUBCcAU/PgTdU40vCvdmlFJ/8Yb4UuSa5aNeS0eeSo8mXBjYH62iNSvSwm9plE0nDZuqPMscjA8OAZgg/Klnco2Ky6bmDzr7fe4zL6vsh3LlgwCsQe3mE2e1lD7pvamprv0YCHUz1aaUzfvrD6hiuygb6BrCYJI+FEgDb7zB0G7y53uu04t4K7HSckfDHiyAoUKaiSiFXwgdpKxjDq9Tl/E1YowJk0JCVk6pwDRhIRaY66qnKzxCWBmpZdH9NZOOvcKw4rB8c0GdeXEcfXw47Uhv9ClM2cMu2bJAOmyAJpS7PpwXZMc63SNL8Q/ewK7D29HanX/E/2boYW6hpP4L2N7+cziIUnzh6apbnpEt/XtxFfDaBZh1rwBOpZKkLAnC99e8UEqfEFXvZvfy9dS3oLJ1KCauVVR5knh8ry0E8jQ=="
nodes: ["hulk", "ironman", "thor"]

# CloudINIT VARIABLES
cloudinit:
  password: "U72^758$YMz6K$pS7*rgzHj#s^"

