- name: Deploy infrastructure
  hosts: localhost
  vars_files:
    - "vars/vault.yml"
  roles:
    - terraform

- name: Install Keycloak
  hosts: keycloak
  remote_user: root
  roles:
    - keycloak
  