---
keycloak_version: "{{ keycloak.version }}"
keycloak_dir: "{{ keycloak.dir }}"
keycloak_archive: "{{ keycloak.archive }}"
keycloak_url: "{{ keycloak.url }}"
keycloak_jboss_home: "{{ keycloak.jboss_home }}"
keycloak_log_dir: "{{ keycloak.log_dir }}"
keycloak_bind_port: "{{ keycloak.port }}"
keycloak_bind_address: "{{ keycloak.bind_address }}"
keycloak_admin_username: "{{ keycloak.admin_username }}"
keycloak_admin_password: "{{ keycloak.password }}"
keycloak_create_admin: "{{ keycloak.create_admin }}"
keycloak_mysql: "{{ database.mysql }}"
keycloak_mysql_connector_version: "{{ database.connector_version }}"
keycloak_mysql_connector_url: "{{ database.connector_url }}"
keycloak_mysql_host: "{{ database.host }}"
keycloak_mysql_user: "{{ database.user}}"
keycloak_mysql_password: "{{ database.password }}"
keycloak_mysql_database: "{{ database.database_name }}"
keycloak_mysql_port: "{{ database.port }}"

...
